name: hw1_dagger
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - tqdm=4.62.1
  - anaconda::pillow
  - nvidia::cudatoolkit=10.1
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - termcolor==1.1.0
    - gym==0.19
    - "stable-baselines3[extra]"
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - pandas==1.3.0
    - ipdb==0.13.9
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - wandb
