device: cuda
run_name: dagger_explore_exponential_decay_high_res

experience_buffer_len: 150000

total_training_episodes: 2000
train_every: 25
num_training_steps: 10000
batch_size: 256
lr: 1e-4
exponential_decay_factor: 2

eval_every: 10
num_eval_episodes: 3
